### ISSUE TITLE
Adding more properties to store items

### ISSUE THREAD

**Issue by DavidDoesDev** [CMClay/metalsmith-lunr#9]
Nice plugin! Is it possible to add multiples refs in the store items (or something along those lines)? For example, if you index by `'filePath'`, and then use lunr.js to search through searchIndex.json, how would you grab the title? Is there a way to make `'title'` and `'filePath'` easily accessible at the same time, using the same json file? I'm trying to use this to make a search-suggest sort of thing. Any tips appreciated. Thanks in advance.

**Comment by CMClay** [comment]
@DavidDoesDev Thanks for the interest in my plugin!
Since my plugin doesn't control the search output, I don't think there's an elegant way to include other file metadata in the lunr search results. You could simply add another field to the file that concatenates the title and the filePath:

``` js
Metalsmith(__dirname)
  .use(lunrRef())
  .use(lunr({
    ref: 'lunrRef'
  }))
  .build(function(err) {
    if (err) throw err;
  });

function lunrRef(opts){
  return function(files, metalsmith, done){
    for (file in files){
      files[file].lunrRef = file + '-' + files[file].title;
    };
    done();
  };
}
```

Let me know if you have any questions. I'll try to reply more promptly.

**Comment by DavidDoesDev** [comment]
You are the man!
